print("\033[31m")
print('You end up in an unfamilair location')
print("\033[0m")
name = input('What is your name? ')
print("Ahh I see your name is {0}".format(name))
fav_video_game = input('What is your favorite game? ')
fav_sport = input('What is your favorite sport? ')
print("You soon realze you are in the world of {0} and getting ready for a {1} match".format(fav_video_game,fav_sport))
print("\033[32m You have an epic battle and become victorious!")